"""Tests for Rust return-type emission and E0308 self-healing."""

from __future__ import annotations

import ast
import subprocess
import tempfile
from pathlib import Path

import pytest

from aero_forge.builder.emitters.rust_emitter import RustEmitter
from aero_forge.builder.spec import (
    EngineSpec,
    function,
    literal,
    module,
    param,
    return_node,
)
from aero_forge.healing.router import try_auto_fix
from aero_forge.scaffold.engine import RustGenerator


def test_rust_emitter_infers_integer_return_for_unannotated_stub() -> None:
    """A stub returning an integer literal must get an ``-> i64`` signature."""
    spec = EngineSpec(
        name="demo",
        root=module(
            children=[
                function(
                    "helper",
                    params=[param("x", "int")],
                    return_type=None,
                    body=[return_node(literal(0))],
                ),
            ]
        ),
    )
    source = RustEmitter().emit(spec)
    assert "pub fn helper(x: i64) -> i64 {" in source
    assert "return 0;" in source


def test_rust_emitter_void_function_emits_bare_return() -> None:
    """A true void function must emit a bare ``return;``."""
    spec = EngineSpec(
        name="demo",
        root=module(
            children=[
                function(
                    "stub",
                    params=[param("x", "int")],
                    return_type="void",
                    body=[return_node(literal(None))],
                ),
            ]
        ),
    )
    source = RustEmitter().emit(spec)
    assert "pub fn stub(x: i64) {" in source
    assert "return;" in source
    assert "return ()" not in source


def test_rust_emitter_integer_stub_compiles() -> None:
    """Integer-return stubs generated by ``RustEmitter`` must compile with ``cargo``."""
    spec = EngineSpec(
        name="demo",
        root=module(
            children=[
                function(
                    "helper",
                    params=[param("x", "int")],
                    return_type=None,
                    body=[return_node(literal(0))],
                ),
                function(
                    "stub",
                    params=[param("x", "int")],
                    return_type=None,
                    body=[return_node(literal(0))],
                ),
            ]
        ),
    )
    source = RustEmitter().emit(spec)
    with tempfile.TemporaryDirectory() as tmp:
        crate = Path(tmp) / "demo"
        crate.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["cargo", "init", "--lib", "--name", "demo", "."],
            cwd=crate,
            check=True,
        )
        (crate / "src" / "lib.rs").write_text(source)
        subprocess.run(["cargo", "build"], cwd=crate, check=True)


def test_rust_generator_overrides_none_annotation_for_integer_return() -> None:
    """A Python function annotated ``-> None`` but returning an int must emit ``-> i64``."""
    source = "def stub(x: int) -> None:\n    return 0\n"
    func = ast.parse(source).body[0]
    assert isinstance(func, ast.FunctionDef)
    generator = RustGenerator(func, "demo", {})
    rust = generator.emit()
    assert "fn _accel_stub(x: i64) -> i64" in rust
    assert "return 0_i64;" in rust


def test_rust_generator_keeps_void_for_bare_return() -> None:
    """A true void function must still emit a bare ``return;``."""
    source = "def f(x: int) -> None:\n    return\n"
    func = ast.parse(source).body[0]
    assert isinstance(func, ast.FunctionDef)
    generator = RustGenerator(func, "demo", {})
    rust = generator.emit()
    assert "fn _accel_f(x: i64)" in rust
    assert "return;" in rust
    assert "-> i64" not in rust


def test_try_auto_fix_patches_e0308_return_mismatch() -> None:
    """The deterministic healer must align Rust return signatures with body values."""
    code = (
        "use pyo3::prelude::*;\n\n"
        "#[allow(unused_variables)]\n"
        '#[pyfunction(name = "stub")]\n'
        "fn _accel_stub(x: i64) {\n"
        "    return 0_i64;\n"
        "}\n"
    )
    log = (
        "error[E0308]: mismatched types\n"
        "  --> src/lib.rs:6:12\n"
        "   |\n"
        "6  | fn _accel_stub(x: i64) {\n"
        "   |    -------------------- expected `()` because of return type\n"
        "7  |     return 0_i64;\n"
        "   |            ^^^^^ expected `()`, found `i64`\n"
    )
    fixed = try_auto_fix(log, code)
    assert fixed is not None
    assert "fn _accel_stub(x: i64) -> i64" in fixed


def test_try_auto_fix_patched_source_compiles() -> None:
    """A patched E0308 ``lib.rs`` must build cleanly with ``cargo``."""
    code = (
        "use pyo3::prelude::*;\n\n"
        "#[allow(unused_variables)]\n"
        '#[pyfunction(name = "stub")]\n'
        "fn _accel_stub(x: i64) {\n"
        "    return 0_i64;\n"
        "}\n"
    )
    log = (
        "error[E0308]: mismatched types\n"
        "  --> src/lib.rs:6:12\n"
        "   |\n"
        "6  | fn _accel_stub(x: i64) {\n"
        "   |    -------------------- expected `()` because of return type\n"
        "7  |     return 0_i64;\n"
        "   |            ^^^^^ expected `()`, found `i64`\n"
    )
    fixed = try_auto_fix(log, code)
    assert fixed is not None
    with tempfile.TemporaryDirectory() as tmp:
        crate = Path(tmp) / "demo"
        crate.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["cargo", "init", "--lib", "--name", "demo", "."],
            cwd=crate,
            check=True,
        )
        cargo_toml = crate / "Cargo.toml"
        cargo_toml.write_text(
            cargo_toml.read_text()
            + '\npyo3 = { version = "0.20", features = ["extension-module"] }\n'
        )
        (crate / "src" / "lib.rs").write_text(fixed)
        subprocess.run(["cargo", "build"], cwd=crate, check=True)
