"""Module tree guard: reify declared-but-missing module files after .aeroc unpack."""

from __future__ import annotations

import ast
import logging
import re
from pathlib import Path
from typing import List, Tuple

logger = logging.getLogger("aero_forge.scaffold.module_guard")

# Rust `mod`/`pub mod` declarations: `pub mod diagnostics;` or `mod foo;`
_RUST_MOD_RE = re.compile(r"^\s*(?:pub\s+)?mod\s+(\w+)\s*;", re.MULTILINE)


def _rust_module_candidates(parent_dir: Path, name: str) -> List[Path]:
    """Return the conventional Rust module file paths for *name* in *parent_dir*."""
    return [
        parent_dir / f"{name}.rs",
        parent_dir / name / "mod.rs",
    ]


def _rust_stub(name: str) -> str:
    return (
        f"// Auto-generated module stub for `{name}`\n"
        f"// Re-generated by aero_forge module tree guard to satisfy declaration.\n\n"
        f"pub fn {name}() {{\n    todo!(\"implement `{name}`\")\n}}\n"
    )


def _python_import_targets(source: str) -> List[Tuple[str, str]]:
    """Return simple top-level module names imported within *source*."""
    targets: List[Tuple[str, str]] = []
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return targets
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                name = alias.name.split(".")[0]
                targets.append((name, alias.asname or name))
        elif isinstance(node, ast.ImportFrom):
            if node.level and node.module:
                # relative import; handled separately
                continue
            if node.module:
                name = node.module.split(".")[0]
                targets.append((name, name))
    return targets


def _python_stub(name: str) -> str:
    return (
        f"# Auto-generated module stub for `{name}`\n"
        f"# Re-generated by aero_forge module tree guard to satisfy import.\n\n"
        f"def __getattr__(name: str):\n"
        f"    raise NotImplementedError(f\"module `{name}` is a stub; implement it before use.\")\n"
    )


def reify_missing_modules(workspace: Path) -> List[Path]:
    """Scan *workspace* for declared modules whose files are absent and create stubs.

    Returns the list of newly created stub paths.
    """
    workspace = Path(workspace).resolve()
    created: List[Path] = []

    # Rust guard
    for rs_file in workspace.rglob("*.rs"):
        if not rs_file.is_file():
            continue
        text = rs_file.read_text(encoding="utf-8")
        parent = rs_file.parent
        for match in _RUST_MOD_RE.finditer(text):
            name = match.group(1)
            for candidate in _rust_module_candidates(parent, name):
                if candidate.is_file():
                    break
            else:
                stub_path = parent / f"{name}.rs"
                stub_path.write_text(_rust_stub(name), encoding="utf-8")
                created.append(stub_path)
                logger.info("Created missing Rust module stub %s", stub_path)

    # Python guard (top-level packages only; avoid deep heuristics)
    for py_file in workspace.rglob("*.py"):
        if not py_file.is_file():
            continue
        text = py_file.read_text(encoding="utf-8")
        parent = py_file.parent
        for name, _alias in _python_import_targets(text):
            target = parent / f"{name}.py"
            pkg_init = parent / name / "__init__.py"
            if target.is_file() or pkg_init.is_file():
                continue
            if parent == workspace:
                # Only create stubs for top-level missing imports to avoid noise.
                target.write_text(_python_stub(name), encoding="utf-8")
                created.append(target)
                logger.info("Created missing Python module stub %s", target)

    return created
