"""Module tree guard: reify declared-but-missing module files after .aeroc unpack."""

from __future__ import annotations

import ast
import logging
import re
from pathlib import Path
from typing import List, Tuple

logger = logging.getLogger("aero_forge.scaffold.module_guard")

# Rust `mod`/`pub mod` declarations: `pub mod diagnostics;` or `mod foo;`
_RUST_MOD_RE = re.compile(r"^\s*(?:pub\s+)?mod\s+(\w+)\s*;", re.MULTILINE)


def _rust_module_candidates(parent_dir: Path, name: str) -> List[Path]:
    """Return the conventional Rust module file paths for *name* in *parent_dir*."""
    return [
        parent_dir / f"{name}.rs",
        parent_dir / name / "mod.rs",
    ]


def _rust_stub(name: str) -> str:
    return (
        f"// Auto-generated module stub for `{name}`\n"
        f"// Re-generated by aero_forge module tree guard to satisfy declaration.\n\n"
        f"pub fn {name}() {{\n    todo!(\"implement `{name}`\")\n}}\n"
    )


def _python_import_targets(source: str) -> List[Tuple[str, str]]:
    """Return simple top-level module names imported within *source*."""
    targets: List[Tuple[str, str]] = []
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return targets
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                name = alias.name.split(".")[0]
                targets.append((name, alias.asname or name))
        elif isinstance(node, ast.ImportFrom):
            if node.level and node.module:
                # relative import; handled separately
                continue
            if node.module:
                name = node.module.split(".")[0]
                targets.append((name, name))
    return targets


def _python_stub(name: str) -> str:
    return (
        f"# Auto-generated module stub for `{name}`\n"
        f"# Re-generated by aero_forge module tree guard to satisfy import.\n\n"
        f"def __getattr__(name: str):\n"
        f"    raise NotImplementedError(f\"module `{name}` is a stub; implement it before use.\")\n"
    )


def ensure_package_structure(workspace: Path) -> List[Path]:
    """Ensure every generated Python sub-directory is a package with ``__init__.py``.

    For each directory that contains ``.py`` files and does not already have an
    ``__init__.py``, one is created (or updated) exporting ``__all__`` with the
    public classes and functions found in that directory.
    """
    workspace = Path(workspace).resolve()
    created: List[Path] = []
    skip_dirs = {"__pycache__", ".git", ".pytest_cache", "venv", ".venv", "node_modules"}
    skip_names = {"test", "tests"}

    # Discover directories that contain Python source files.
    package_dirs: set = set()
    for py_file in workspace.rglob("*.py"):
        if not py_file.is_file():
            continue
        if py_file.name == "__init__.py":
            package_dirs.add(py_file.parent)
            continue
        if any(part in skip_dirs or part.lower() in skip_names for part in py_file.parts):
            continue
        package_dirs.add(py_file.parent)

    for package_dir in sorted(package_dirs):
        init_path = package_dir / "__init__.py"
        public_names: List[str] = []
        for py_file in sorted(package_dir.glob("*.py")):
            if py_file.name == "__init__.py":
                continue
            try:
                text = py_file.read_text(encoding="utf-8")
                tree = ast.parse(text)
            except (SyntaxError, OSError, UnicodeDecodeError):
                continue
            for node in tree.body:
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    if not node.name.startswith("_"):
                        public_names.append(node.name)

        if not init_path.is_file():
            all_list = ", ".join(repr(n) for n in public_names)
            init_path.write_text(f"__all__ = [{all_list}]\n", encoding="utf-8")
            created.append(init_path)
            logger.info("Created package init %s", init_path)
        else:
            # If an __init__.py exists but has no __all__, append a generated one.
            existing = init_path.read_text(encoding="utf-8")
            if "__all__" not in existing:
                all_list = ", ".join(repr(n) for n in public_names)
                init_path.write_text(
                    existing.rstrip("\n") + f"\n\n__all__ = [{all_list}]\n",
                    encoding="utf-8",
                )
                created.append(init_path)

    return created


def reify_missing_modules(workspace: Path) -> List[Path]:
    """Scan *workspace* for declared modules whose files are absent and create stubs.

    Returns the list of newly created stub paths.
    """
    workspace = Path(workspace).resolve()
    created: List[Path] = []

    # Rust guard
    for rs_file in workspace.rglob("*.rs"):
        if not rs_file.is_file():
            continue
        text = rs_file.read_text(encoding="utf-8")
        parent = rs_file.parent
        for match in _RUST_MOD_RE.finditer(text):
            name = match.group(1)
            for candidate in _rust_module_candidates(parent, name):
                if candidate.is_file():
                    break
            else:
                stub_path = parent / f"{name}.rs"
                stub_path.write_text(_rust_stub(name), encoding="utf-8")
                created.append(stub_path)
                logger.info("Created missing Rust module stub %s", stub_path)

    # Python guard (top-level packages only; avoid deep heuristics)
    for py_file in workspace.rglob("*.py"):
        if not py_file.is_file():
            continue
        text = py_file.read_text(encoding="utf-8")
        parent = py_file.parent
        for name, _alias in _python_import_targets(text):
            target = parent / f"{name}.py"
            pkg_init = parent / name / "__init__.py"
            if target.is_file() or pkg_init.is_file():
                continue
            if parent == workspace:
                # Only create stubs for top-level missing imports to avoid noise.
                target.write_text(_python_stub(name), encoding="utf-8")
                created.append(target)
                logger.info("Created missing Python module stub %s", target)

    return created
