"""Deterministic self-healing facade for cross-language build failures.

The :class:`Healer` orchestrates the proof-theoretic repair pipeline:
HIN energy checks are not performed here (they are part of the native build
evaluation), but all structural rewrites, FFI morphism synthesis, and GoI
matrix boundary validation flow through deterministic helpers.  LLM calls are
kept out of the execution/repair loop; they are only used by upstream callers
for intent interpretation and human-facing summaries.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

from aero_forge.healing.evaluator import HealingStrategy, LogEvaluator
from aero_forge.healing.orchestrator import HealingOrchestrator
from aero_forge.healing.router import try_auto_fix
from aero_forge.overlay.apply import persist_text_to_disk

_C_ABI_LOAD_RE = re.compile(
    r"(?:OSError|FileNotFoundError|ImportError).*\b(?:cannot load library|Could not find native library|cannot find.*\.(?:so|dylib|dll))\b",
    re.IGNORECASE,
)

_C_ABI_SYMBOL_RE = re.compile(
    r"(?:undefined symbol:\s*(?P<sym1>\w+)|AttributeError:.*has no attribute ['\"](?P<sym2>\w+)['\"])",
    re.IGNORECASE,
)


def _extract_c_abi_symbol(error_log: str) -> Optional[str]:
    match = _C_ABI_SYMBOL_RE.search(error_log)
    if not match:
        return None
    return match.group("sym1") or match.group("sym2")


def _discover_native_library(
    workspace: Path, so_name: Optional[str] = None
) -> Optional[Path]:
    """Return the first compiled native library found under *workspace*."""
    candidates: List[Path] = []
    if so_name:
        for ext in (".so", ".dylib", ".dll"):
            candidates.extend(workspace.rglob(so_name + ext))
            candidates.extend(workspace.rglob("lib" + so_name + ext))
    candidates.extend(workspace.rglob("*.so"))
    candidates.extend(workspace.rglob("*.dylib"))
    candidates.extend(workspace.rglob("*.dll"))
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    return None


def _patch_loader_candidates(code: str, so_path: Path) -> Optional[str]:
    """Inject *so_path* as the first candidate in a generated ctypes loader.

    The loader generated by ``_ctypes_loader_source`` declares ``_SO_CANDIDATES``
    and uses ``_find_library`` to select the first existing candidate.  If the
    compiled library exists but the loader's search path is stale, prepending the
    discovered absolute path repairs directory mapping without brittle edits.
    """
    match = re.search(r"(_SO_CANDIDATES\s*=\s*\[)[^\]]*", code, re.DOTALL)
    if not match:
        return None
    insert = match.end()
    candidate = f"pathlib.Path({str(so_path)!r}), "
    return code[:insert] + candidate + code[insert:]


def _patch_missing_c_symbol_in_loader(code: str, symbol: str) -> Optional[str]:
    """Make the ctypes loader tolerate a missing *symbol* by adding a fallback.

    When a C-ABI symbol is missing from the shared library, the Python wrapper
    that does ``_LIB.<symbol>`` raises ``AttributeError``.  This patch wraps the
    attribute lookup with ``getattr`` and, if the symbol is unavailable, raises
    an actionable ``RuntimeError`` that preserves the original contract.
    """
    pattern = re.compile(
        rf"(\s)({re.escape(symbol)})\s*=\s*_LIB\.{re.escape(symbol)}\b"
    )
    if not pattern.search(code):
        return None

    def repl(match: re.Match) -> str:
        indent = match.group(1)
        name = match.group(2)
        return (
            f"{indent}{name} = getattr(_LIB, {name!r}, None)\n"
            f"{indent}if {name} is None:\n"
            f'{indent}    raise RuntimeError(f"C-ABI symbol {name!r} is not exported by {{_SO}}")'
        )

    return pattern.sub(repl, code)


class Healer:
    """Deterministic, proof-theoretic self-healing entry point.

    ``Healer`` is intentionally thin: it classifies failures, attempts the
    cheapest deterministic AST/FFI patches first, and escalates to the full
    ``HealingOrchestrator`` only when a deterministic repair is not available.
    """

    def __init__(
        self,
        workspace: Path,
        llm_provider: str = "deepseek",
        llm_model: Optional[str] = None,
        log_callback: Optional[Callable[[str, str, str], None]] = None,
    ) -> None:
        self.workspace = Path(workspace).resolve()
        self.orchestrator = HealingOrchestrator(
            workspace=self.workspace,
            llm_provider=llm_provider,
            llm_model=llm_model,
            log_callback=log_callback,
        )
        self.log_callback = log_callback or self._default_log

    @staticmethod
    def _default_log(level: str, prefix: str, message: str) -> None:
        pass

    def diagnose(
        self, error_log: str, command: str = "", exit_code: int = 1
    ) -> Dict[str, Any]:
        """Return a structured diagnosis for *error_log*."""
        evaluator = LogEvaluator()
        return evaluator.evaluate_log(command, exit_code, error_log)

    def _target_path(self, target_file: Optional[str]) -> Path:
        if not target_file:
            return self.workspace / "main.py"
        target = (self.workspace / target_file).resolve()
        if not str(target).startswith(str(self.workspace)):
            return self.workspace / "main.py"
        return target

    def _try_c_abi_directory_fix(
        self,
        error_log: str,
        target_file: Optional[str],
        diagnosis: Dict[str, Any],
    ) -> Optional[Dict[str, Any]]:
        """Attempt to repair a stale ctypes loader path."""
        # The loader is usually the Python __init__/bridge file referenced by the traceback.
        target = self._target_path(target_file or diagnosis.get("target_file"))
        if target.suffix != ".py" or not target.is_file():
            return None

        original = target.read_text(encoding="utf-8")
        if "_SO_CANDIDATES" not in original and "ctypes.CDLL" not in original:
            return None

        so_name_match = re.search(r"_SO_NAME\s*=\s*['\"]([^'\"]+)['\"]", original)
        so_name = so_name_match.group(1) if so_name_match else None
        so_path = _discover_native_library(self.workspace, so_name)
        if not so_path:
            return None

        patched = _patch_loader_candidates(original, so_path)
        if patched and patched != original:
            persist_text_to_disk(target, patched)
            self.log_callback(
                "info", "HEAL", f"Patched ctypes loader candidates in {target.name}"
            )
            return {
                "status": "success",
                "strategy_used": HealingStrategy.AST.value,
                "patched_files": [str(target.relative_to(self.workspace))],
                "error_message": None,
                "target_file": str(target.relative_to(self.workspace)),
                "diagnosis": diagnosis,
            }
        return None

    def _try_c_abi_symbol_fix(
        self,
        error_log: str,
        target_file: Optional[str],
        diagnosis: Dict[str, Any],
    ) -> Optional[Dict[str, Any]]:
        """Attempt a deterministic patch for a missing C-ABI symbol export."""
        symbol = _extract_c_abi_symbol(error_log)
        if not symbol:
            return None

        target = self._target_path(target_file or diagnosis.get("target_file"))
        if target.suffix != ".py" or not target.is_file():
            return None

        original = target.read_text(encoding="utf-8")
        patched = _patch_missing_c_symbol_in_loader(original, symbol)
        if patched and patched != original:
            persist_text_to_disk(target, patched)
            self.log_callback(
                "info",
                "HEAL",
                f"Protected ctypes loader against missing symbol {symbol!r}",
            )
            return {
                "status": "success",
                "strategy_used": HealingStrategy.AST.value,
                "patched_files": [str(target.relative_to(self.workspace))],
                "error_message": None,
                "target_file": str(target.relative_to(self.workspace)),
                "diagnosis": diagnosis,
            }
        return None

    def heal(
        self,
        error_log: str,
        command: str = "",
        exit_code: int = 1,
        target_file: Optional[str] = None,
        force_llm: bool = False,
    ) -> Dict[str, Any]:
        """Classify *error_log*, apply deterministic repairs, and escalate if needed."""
        diagnosis = self.diagnose(error_log, command, exit_code)
        error_type = diagnosis.get("error_type") or "unknown"

        if not force_llm and error_type == "c_abi_library_load_error":
            result = self._try_c_abi_directory_fix(error_log, target_file, diagnosis)
            if result:
                return result

        if not force_llm and error_type == "c_abi_symbol_error":
            result = self._try_c_abi_symbol_fix(error_log, target_file, diagnosis)
            if result:
                return result

        return self.orchestrator.heal(
            error_log,
            command=command,
            exit_code=exit_code,
            target_file=target_file,
            force_llm=force_llm,
        )

    def execute_healing_pass(
        self,
        error_log: str,
        command: str = "",
        exit_code: int = 1,
        target_file: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Alias for :meth:`heal` matching the deterministic self-healing pipeline name."""
        return self.heal(
            error_log, command=command, exit_code=exit_code, target_file=target_file
        )
