"""C++ target emitter for aero-forge engine specs."""

from __future__ import annotations

from typing import Any, List, Optional

from aero_forge.builder.emitters.base import BaseEmitter
from aero_forge.builder.spec import ASTNode, EngineSpec


class CppEmitter(BaseEmitter):
    """Emit syntactically valid C++17 source from an engine spec.

    When ``c_abi`` is ``True`` the emitter produces a dynamic shared library with
    ``extern "C"`` exported symbols so the compiled artifact can be loaded via
    ``ctypes`` / C-ABI in the native acceleration bridge.
    """

    target_language = "cpp"

    def __init__(self, c_abi: bool = False, indent: Optional[str] = None) -> None:
        super().__init__(indent=indent)
        self.c_abi = c_abi
        self._functions: List[ASTNode] = []
        self._declared_vars: Optional[set] = None

    def _emit_preamble(self, spec: EngineSpec) -> None:
        self._write("// Auto-generated by aero-forge polyglot emitter.")
        self._write("#include <cstdint>")
        self._write("#include <cstddef>")
        self._write("#include <cstdlib>")
        self._write("#include <cstring>")
        self._write("#include <iostream>")
        self._write("#include <string>")
        self._write("#include <vector>")
        self._write("#include <map>")
        self._write("#include <cmath>")
        self._write("#include <tuple>")
        if self.c_abi:
            self._write("")
            self._write('#ifdef _WIN32')
            self._write('#define AERO_EXPORT __declspec(dllexport)')
            self._write('#else')
            self._write('#define AERO_EXPORT __attribute__((visibility("default")))')
            self._write('#endif')
        self._write("")

    def _emit_module(self, node: ASTNode, indent_level: int) -> None:
        self._emit_children(node.children, indent_level)

    def _internal_name(self, name: str) -> str:
        """Name used for the C++ implementation when emitting C-ABI wrappers."""
        if self.c_abi:
            return f"aero_impl_{name}"
        return name

    def _func_name(self, name: str) -> str:
        """Reference to a function (internal name in C-ABI mode)."""
        if not name:
            return ""
        # Fully-qualified C++ names (std::...) and method calls should not be prefixed.
        if "::" in name:
            return name
        # Method calls on vector/list objects should not be prefixed; map Python
        # ``append`` to the C++ vector equivalent ``push_back``.
        if "." in name:
            if name.endswith(".append"):
                name = name[: -len(".append")] + ".push_back"
            return name
        return self._internal_name(name)

    def _emit_function(self, node: ASTNode, indent_level: int) -> None:
        params = node.params
        param_strs: List[str] = []
        declared_before = self._declared_vars
        self._declared_vars = {p.name for p in params if p.name != "self"}
        for p in params:
            if p.name == "self":
                continue
            if p.type_hint:
                param_strs.append(f"{self._map_type(p.type_hint)} {p.name}")
            else:
                param_strs.append(f"auto {p.name}")

        ret = self._function_return_type(node)
        name = self._internal_name(node.name or "fn")
        linkage = "static " if self.c_abi else ""
        sig = f"{linkage}{ret} {name}({', '.join(param_strs)})"

        self._write("")
        self._write(f"{sig} {{", indent_level)
        body = node.body
        if body:
            self._emit_children(body, indent_level + 1)
        elif self.c_abi and self._is_known_algorithm(node.name or ""):
            self._emit_known_algorithm(node, indent_level + 1)
        else:
            for p in params:
                if p.name != "self":
                    self._write(f"(void){p.name};", indent_level + 1)
            if ret == "void":
                self._write("return;", indent_level + 1)
            else:
                self._write("return {};", indent_level + 1)
        self._write("}", indent_level)

        self._declared_vars = declared_before
        if self.c_abi:
            self._functions.append(node)

    def _is_known_algorithm(self, name: str) -> bool:
        """Return True when the emitter has a built-in numerical implementation for *name*."""
        return name.lower() in {"sliding_window_dtw", "dtw"}

    def _emit_known_algorithm(self, node: ASTNode, indent_level: int) -> None:
        """Emit a full C++ implementation for well-known numerical contracts.

        Currently supports a Sakoe-Chiba constrained sliding-window DTW. The
        generated function matches the C-ABI wrapper emitted by
        ``_emit_c_abi_wrapper`` and uses ``std::vector<double>`` for the two
        input sequences and an ``int64_t`` window parameter.
        """
        params = [p for p in node.params if p.name != "self"]
        if len(params) < 3:
            self._write("// TODO: known algorithm signature not matched", indent_level)
            return

        a = params[0].name or "a"
        b = params[1].name or "b"
        window = params[2].name or "window"

        for line in [
            f"if ({a}.empty() || {b}.empty() || {window} <= 0) return -1.0;",
            f"int64_t win = static_cast<int64_t>({window});",
            f"int64_t n = static_cast<int64_t>({a}.size());",
            f"int64_t m = static_cast<int64_t>({b}.size());",
            f"if (std::llabs(n - m) > win) return -2.0;",
            "const double INF = 1e100;",
            "std::vector<double> prev(m, INF), cur(m, INF);",
            "for (int64_t j = 0; j < m; ++j) {",
            "    if (j > win) continue;",
            f"    prev[j] = std::fabs({a}[0] - {b}[j]);",
            "}",
            "for (int64_t i = 1; i < n; ++i) {",
            "    cur.assign(m, INF);",
            "    for (int64_t j = 0; j < m; ++j) {",
            "        if (i - j > win || j - i > win) continue;",
            f"        double cost = std::fabs({a}[i] - {b}[j]);",
            "        double best = prev[j];",
            "        if (j > 0 && cur[j - 1] < best) best = cur[j - 1];",
            "        if (j > 0 && prev[j - 1] < best) best = prev[j - 1];",
            "        cur[j] = cost + best;",
            "    }",
            "    prev.swap(cur);",
            "}",
            "return prev[m - 1];",
        ]:
            self._write(line, indent_level)
        if self._declared_vars is not None:
            for var in ("win", "n", "m", "INF", "prev", "cur", "i", "j", "cost", "best"):
                self._declared_vars.add(var)

    def _function_return_type(self, node: ASTNode) -> str:
        """Return the C++ return type for *node*, falling back to ``auto`` when needed."""
        if node.type_hint:
            return self._map_type(node.type_hint)
        # If the body returns a value, use auto deduction (C++14+). Otherwise void.
        for child in node.body:
            if child.kind == "return" and child.children:
                return "auto"
        return "void"

    def _emit_struct(self, node: ASTNode, indent_level: int) -> None:
        self._write("")
        self._write(f"struct {node.name} {{", indent_level)
        for field in node.children:
            if field.kind != "field":
                continue
            type_str = self._map_type(field.type_hint) if field.type_hint else "auto"
            self._write(f"{type_str} {field.name};", indent_level + 1)
        self._write("};", indent_level)

    def _emit_binding(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        if self._declared_vars is not None and node.name not in self._declared_vars:
            cpp_type = self._map_type(node.type_hint) if node.type_hint else "auto"
            self._write(f"{cpp_type} {node.name} = {value_str};", indent_level)
            self._declared_vars.add(node.name)
        else:
            self._write(f"{node.name} = {value_str};", indent_level)

    def _emit_return(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        self._write(f"return {value_str};", indent_level)

    def _emit_call(self, node: ASTNode, indent_level: int) -> None:
        """Emit a call node used as a standalone statement."""
        self._write(f"{self._expr(node)};", indent_level)

    def _emit_import(self, node: ASTNode, indent_level: int) -> None:
        value = str(node.value or "")
        if value.startswith("<") and value.endswith(">"):
            self._write(f"#include {value}", indent_level)
        else:
            self._write(f'#include "{value}"', indent_level)

    def _emit_comment(self, node: ASTNode, indent_level: int) -> None:
        for line in str(node.value or "").splitlines():
            self._write(f"// {line}", indent_level)

    def _emit_if(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        condition = self._expr(node.children[0])
        self._write(f"if ({condition}) {{", indent_level)
        if len(node.children) > 1:
            self._emit_children(node.children[1].children, indent_level + 1)
        self._write("}", indent_level)
        if len(node.children) > 2:
            self._write("else {", indent_level)
            self._emit_children(node.children[2].children, indent_level + 1)
            self._write("}", indent_level)

    def _emit_for(self, node: ASTNode, indent_level: int) -> None:
        if len(node.children) < 2:
            return
        iter_node = node.children[0]
        body = node.children[1]
        var = node.name or "i"

        if iter_node.kind == "call" and iter_node.name == "range":
            args = iter_node.children
            start = "0"
            stop: str = ""
            step = "1"
            if len(args) == 1:
                stop = self._expr(args[0])
            elif len(args) == 2:
                start = self._expr(args[0])
                stop = self._expr(args[1])
            elif len(args) >= 3:
                start = self._expr(args[0])
                stop = self._expr(args[1])
                step = self._expr(args[2])
            predeclared = self._declared_vars is not None and var in self._declared_vars
            if not predeclared and self._declared_vars is not None:
                self._declared_vars.add(var)
            init = f"{var} = {start}" if predeclared else f"auto {var} = {start}"
            if len(args) >= 3:
                cond = f"(({step} > 0 && {var} < {stop}) || ({step} < 0 && {var} > {stop}))"
                self._write(
                    f"for ({init}; {cond}; {var} += {step}) {{",
                    indent_level,
                )
            else:
                self._write(
                    f"for ({init}; {var} < {stop}; ++{var}) {{",
                    indent_level,
                )
        else:
            iter_expr = self._expr(iter_node)
            self._write(f"for (auto {var} : {iter_expr}) {{", indent_level)

        self._emit_children(body.children, indent_level + 1)
        self._write("}", indent_level)

    def _emit_while(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        condition = self._expr(node.children[0])
        self._write(f"while ({condition}) {{", indent_level)
        if len(node.children) > 1:
            self._emit_children(node.children[1].children, indent_level + 1)
        self._write("}", indent_level)

    def _emit_aug_assign(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        op = str(node.value or "+")
        value = self._expr(node.children[0])
        self._write(f"{node.name} {op}= {value};", indent_level)

    def _emit_expression_to_string(self, node: ASTNode) -> str:
        if node.kind == "subscript":
            if len(node.children) < 2:
                raise EmitterError("subscript node missing value or index")
            return f"{self._expr(node.children[0])}[{self._expr(node.children[1])}]"
        if node.kind == "unary_op":
            if not node.children:
                raise EmitterError("unary_op node missing operand")
            return f"({node.name}{self._expr(node.children[0])})"
        if node.kind == "call":
            args = ", ".join(self._expr(c) for c in node.children)
            return f"{self._func_name(node.name)}({args})"
        return super()._emit_expression_to_string(node)

    def _emit_postamble(self, spec: EngineSpec) -> None:
        if not self.c_abi:
            return
        self._write("")
        self._write("// C-ABI exported wrappers")
        for func in self._functions:
            self._emit_c_abi_wrapper(func)
        self._write("")
        self._write("extern \"C\" {")
        for free_type, ctype in [("i64", "int64_t"), ("f64", "double"), ("bool", "bool")]:
            self._write(
                f"    AERO_EXPORT void free_buffer_{free_type}({ctype}* ptr, size_t) {{ delete[] ptr; }}",
                0,
            )
        self._write("}")

    def _emit_c_abi_wrapper(self, node: ASTNode) -> None:
        """Emit an ``extern "C"`` wrapper that exposes *node* with a ctypes-compatible ABI."""
        name = node.name or "fn"
        internal = self._internal_name(name)
        params = [p for p in node.params if p.name != "self"]

        cpp_ret = self._function_return_type(node)
        is_array_return = cpp_ret.startswith("std::vector<")
        tuple_types = self._tuple_scalar_types(node.type_hint)
        is_tuple_return = bool(tuple_types)

        c_params: List[str] = []
        call_args: List[str] = []
        setup: List[str] = []
        for p in params:
            if p.type_hint and self._is_list_type(p.type_hint):
                elem = self._c_elem_type(p.type_hint)
                c_params.append(f"const {elem}* {p.name}")
                c_params.append(f"size_t {p.name}_len")
                inner = self._map_type(p.type_hint)  # std::vector<...>
                setup.append(f"    {inner} {p.name}_vec({p.name}, {p.name} + {p.name}_len);")
                call_args.append(f"{p.name}_vec")
            else:
                c_type = self._c_scalar_type(p.type_hint)
                c_params.append(f"{c_type} {p.name}")
                call_args.append(p.name)

        if is_array_return:
            c_params.append("size_t* out_len")
        if is_tuple_return:
            for i, t in enumerate(tuple_types):
                c_params.append(f"{self._c_scalar_type(t)}* out_{i}")

        self._write(f"extern \"C\" AERO_EXPORT {self._c_return_type(node.type_hint)} {name}({', '.join(c_params)}) {{")
        for line in setup:
            self._write(line, 1)

        if is_array_return:
            inner = self._vector_inner_type(cpp_ret)
            self._write(f"    auto _result = {internal}({', '.join(call_args)});", 1)
            self._write(f"    *out_len = _result.size();", 1)
            self._write(f"    {inner}* _out = new {inner}[_result.size()];", 1)
            self._write(f"    std::memcpy(_out, _result.data(), _result.size() * sizeof({inner}));", 1)
            self._write(f"    return _out;", 1)
        elif is_tuple_return:
            self._write(f"    auto _result = {internal}({', '.join(call_args)});", 1)
            for i in range(len(tuple_types)):
                self._write(f"    *out_{i} = std::get<{i}>(_result);", 1)
            self._write("    return 0;", 1)
        else:
            self._write(f"    return {internal}({', '.join(call_args)});", 1)

        self._write("}")

    def _map_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "auto"
        type_map = {
            "int": "int64_t" if self.c_abi else "int",
            "i32": "int32_t",
            "i64": "int64_t",
            "float": "double" if self.c_abi else "float",
            "f32": "float",
            "f64": "double",
            "double": "double",
            "str": "std::string",
            "string": "std::string",
            "bool": "bool",
            "void": "void",
            "None": "void",
            "list": "std::vector<auto>",
            "dict": "std::map<std::string, auto>",
        }
        if type_hint.startswith("list["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "auto"
            return f"std::vector<{self._map_type(inner)}>"
        if type_hint.startswith("tuple[") and type_hint.endswith("]"):
            inner = type_hint[6:-1]
            parts = [self._map_type(p.strip()) for p in inner.split(",")]
            return f"std::tuple<{', '.join(parts)}>"
        if type_hint.startswith("dict["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "std::string, auto"
            parts = inner.split(",", 1)
            k = self._map_type(parts[0].strip()) if parts else "std::string"
            v = self._map_type(parts[1].strip()) if len(parts) > 1 else "auto"
            return f"std::map<{k}, {v}>"
        return type_map.get(type_hint, type_hint)

    def _is_list_type(self, type_hint: str) -> bool:
        return type_hint.startswith("list[") or type_hint == "list"

    def _is_scalar_tuple_return(self, type_hint: Optional[str]) -> bool:
        if not type_hint or not type_hint.startswith("tuple[") or not type_hint.endswith("]"):
            return False
        inner = type_hint[6:-1]
        for part in inner.split(","):
            ct = self._c_scalar_type(part.strip())
            if ct == "void*" or ct == "auto" or ct.startswith("std::"):
                return False
        return True

    def _tuple_scalar_types(self, type_hint: Optional[str]) -> List[str]:
        if not self._is_scalar_tuple_return(type_hint):
            return []
        return [p.strip() for p in type_hint[6:-1].split(",")]

    def _c_scalar_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "double"
        if type_hint == "int":
            return "int64_t"
        if type_hint == "float":
            return "double"
        if type_hint == "bool":
            return "bool"
        if self._is_list_type(type_hint):
            return "void*"
        return self._map_type(type_hint)

    def _c_elem_type(self, type_hint: str) -> str:
        """Element type used in C-ABI array pointers."""
        if not type_hint:
            return "double"
        inner = type_hint[5:-1].strip() if type_hint.startswith("list[") and type_hint.endswith("]") else type_hint
        if inner == "int":
            return "int64_t"
        if inner == "float":
            return "double"
        if inner == "bool":
            return "bool"
        return self._map_type(inner)

    def _c_return_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "void"
        if self._is_list_type(type_hint):
            return f"{self._c_elem_type(type_hint)}*"
        if self._is_scalar_tuple_return(type_hint):
            return "int"
        return self._c_scalar_type(type_hint)

    def _vector_inner_type(self, vector_type: str) -> str:
        """Extract the inner type from ``std::vector<T>``."""
        if vector_type.startswith("std::vector<") and vector_type.endswith(">"):
            return vector_type[len("std::vector<"):-1]
        return "double"

    def _bool_literal(self, value: bool) -> str:
        return "true" if value else "false"

    def _none_literal(self) -> str:
        return "{}"

    def _list_literal(self, children: List[ASTNode]) -> str:
        items = ", ".join(self._expr(c) for c in children)
        return f"{{{items}}}"

    def _dict_literal(self, pairs: List[ASTNode]) -> str:
        entries = []
        for pair in pairs:
            k, v = pair.children
            entries.append(f"{{{self._expr(k)}, {self._expr(v)}}}")
        return f"std::map<std::string, int>{{{', '.join(entries)}}}"

    def _string_literal(self, value: str) -> str:
        return f'std::string("{value}")'

    def _literal(self, value: Any) -> str:
        if isinstance(value, str):
            return self._string_literal(value)
        if self.c_abi and isinstance(value, int) and not isinstance(value, bool):
            return f"{value}LL"
        return super()._literal(value)
