"""C++ target emitter for aero-forge engine specs."""

from __future__ import annotations

from typing import List, Optional

from aero_forge.builder.emitters.base import BaseEmitter
from aero_forge.builder.spec import ASTNode, EngineSpec


class CppEmitter(BaseEmitter):
    """Emit syntactically valid C++17 source from an engine spec."""

    target_language = "cpp"

    def _emit_preamble(self, spec: EngineSpec) -> None:
        self._write("// Auto-generated by aero-forge polyglot emitter.")
        self._write("#include <iostream>")
        self._write("#include <string>")
        self._write("#include <vector>")
        self._write("#include <map>")
        self._write("")

    def _emit_module(self, node: ASTNode, indent_level: int) -> None:
        self._emit_children(node.children, indent_level)

    def _emit_function(self, node: ASTNode, indent_level: int) -> None:
        params = node.params
        param_strs: List[str] = []
        for p in params:
            if p.name == "self":
                continue
            if p.type_hint:
                param_strs.append(f"{self._map_type(p.type_hint)} {p.name}")
            else:
                param_strs.append(f"auto {p.name}")

        ret = self._map_type(node.type_hint) if node.type_hint else "void"
        sig = f"{ret} {node.name}({', '.join(param_strs)})"

        self._write("")
        self._write(f"{sig} {{", indent_level)
        body = node.body
        if body:
            self._emit_children(body, indent_level + 1)
        else:
            self._write("// TODO", indent_level + 1)
        self._write("}", indent_level)

    def _emit_struct(self, node: ASTNode, indent_level: int) -> None:
        self._write("")
        self._write(f"struct {node.name} {{", indent_level)
        for field in node.children:
            if field.kind != "field":
                continue
            type_str = self._map_type(field.type_hint) if field.type_hint else "auto"
            self._write(f"{type_str} {field.name};", indent_level + 1)
        self._write("};", indent_level)

    def _emit_binding(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        cpp_type = self._map_type(node.type_hint) if node.type_hint else "auto"
        self._write(f"{cpp_type} {node.name} = {value_str};", indent_level)

    def _emit_return(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        self._write(f"return {value_str};", indent_level)

    def _emit_import(self, node: ASTNode, indent_level: int) -> None:
        value = str(node.value or "")
        if value.startswith("<") and value.endswith(">"):
            self._write(f"#include {value}", indent_level)
        else:
            self._write(f'#include "{value}"', indent_level)

    def _emit_comment(self, node: ASTNode, indent_level: int) -> None:
        for line in str(node.value or "").splitlines():
            self._write(f"// {line}", indent_level)

    def _emit_if(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        condition = self._expr(node.children[0])
        self._write(f"if ({condition}) {{", indent_level)
        if len(node.children) > 1:
            self._emit_children(node.children[1].children, indent_level + 1)
        self._write("}", indent_level)
        if len(node.children) > 2:
            self._write("else {", indent_level)
            self._emit_children(node.children[2].children, indent_level + 1)
            self._write("}", indent_level)

    def _map_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "void"
        type_map = {
            "int": "int",
            "i32": "int32_t",
            "i64": "int64_t",
            "float": "float",
            "f32": "float",
            "f64": "double",
            "double": "double",
            "str": "std::string",
            "string": "std::string",
            "bool": "bool",
            "void": "void",
            "None": "void",
            "list": "std::vector<auto>",
            "dict": "std::map<std::string, auto>",
        }
        if type_hint.startswith("list["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "auto"
            return f"std::vector<{self._map_type(inner)}>"
        if type_hint.startswith("dict["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "std::string, auto"
            parts = inner.split(",", 1)
            k = self._map_type(parts[0].strip()) if parts else "std::string"
            v = self._map_type(parts[1].strip()) if len(parts) > 1 else "auto"
            return f"std::map<{k}, {v}>"
        return type_map.get(type_hint, type_hint)

    def _bool_literal(self, value: bool) -> str:
        return "true" if value else "false"

    def _none_literal(self) -> str:
        return "{}"

    def _list_literal(self, children: List[ASTNode]) -> str:
        items = ", ".join(self._expr(c) for c in children)
        return f"{{{items}}}"

    def _dict_literal(self, pairs: List[ASTNode]) -> str:
        entries = []
        for pair in pairs:
            k, v = pair.children
            entries.append(f"{{{self._expr(k)}, {self._expr(v)}}}")
        return f"std::map<std::string, int>{{{', '.join(entries)}}}"

    def _string_literal(self, value: str) -> str:
        return f'std::string("{value}")'

    def _literal(self, value: Any) -> str:
        if isinstance(value, str):
            return self._string_literal(value)
        return super()._literal(value)
