"""Python target emitter for aero-forge engine specs."""

from __future__ import annotations

import ast
import json
from typing import List, Optional

from aero_forge.builder.emitters.base import (
    BaseEmitter,
    BoundaryContract,
    CapabilityDescriptor,
    CodeArtifact,
    EmitterRegistry,
    PolyglotEmitterPlugin,
)
from aero_forge.builder.spec import ASTNode, EngineSpec, function, module


class PythonEmitter(BaseEmitter):
    """Emit syntactically valid Python 3 source from an engine spec."""

    target_language = "python"

    def _emit_preamble(self, spec: EngineSpec) -> None:
        self._write('"""Auto-generated by aero-forge polyglot emitter."""')
        self._write("from typing import Any, List, Dict, Optional")
        self._write("")

    def _emit_module(self, node: ASTNode, indent_level: int) -> None:
        self._emit_children(node.children, indent_level)

    def _emit_function(self, node: ASTNode, indent_level: int) -> None:
        params = node.params
        param_strs: List[str] = []
        for p in params:
            if p.type_hint:
                param_strs.append(f"{p.name}: {self._map_type(p.type_hint)}")
            else:
                param_strs.append(p.name or "_")
        # Variadic fallback so caller arity mismatches do not crash execution.
        param_strs.extend(["*args", "**kwargs"])

        sig = f"def {node.name}({', '.join(param_strs)})"
        if node.type_hint:
            sig += f" -> {self._map_type(node.type_hint)}"
        sig += ":"

        self._write("")
        self._write(sig, indent_level)
        body = node.body
        if body:
            self._emit_children(body, indent_level + 1)
        else:
            self._write("pass", indent_level + 1)

    def _emit_struct(self, node: ASTNode, indent_level: int) -> None:
        self._write("")
        self._write(f"class {node.name}:", indent_level)
        if node.children:
            for field in node.children:
                if field.kind != "field":
                    continue
                type_str = (
                    f": {self._map_type(field.type_hint)}" if field.type_hint else ""
                )
                self._write(f"{field.name}{type_str}", indent_level + 1)
        else:
            self._write("pass", indent_level + 1)

    def _emit_binding(self, node: ASTNode, indent_level: int) -> None:
        value_str = (
            self._expr(node.children[0]) if node.children else self._literal(node.value)
        )
        if node.type_hint:
            self._write(
                f"{node.name}: {self._map_type(node.type_hint)} = {value_str}",
                indent_level,
            )
        else:
            self._write(f"{node.name} = {value_str}", indent_level)

    def _emit_return(self, node: ASTNode, indent_level: int) -> None:
        value_str = (
            self._expr(node.children[0]) if node.children else self._literal(node.value)
        )
        self._write(f"return {value_str}", indent_level)

    def _emit_import(self, node: ASTNode, indent_level: int) -> None:
        self._write(f"import {node.value}", indent_level)

    def _emit_comment(self, node: ASTNode, indent_level: int) -> None:
        for line in str(node.value or "").splitlines():
            self._write(f"# {line}", indent_level)

    def _emit_if(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        condition = self._expr(node.children[0])
        self._write(f"if {condition}:", indent_level)
        if len(node.children) > 1:
            self._emit_children(node.children[1].children, indent_level + 1)
        else:
            self._write("pass", indent_level + 1)
        if len(node.children) > 2:
            self._write("else:", indent_level)
            self._emit_children(node.children[2].children, indent_level + 1)

    def _map_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "Any"
        type_map = {
            "int": "int",
            "i32": "int",
            "i64": "int",
            "float": "float",
            "f32": "float",
            "f64": "float",
            "double": "float",
            "str": "str",
            "string": "str",
            "bool": "bool",
            "void": "None",
            "None": "None",
            "list": "list[Any]",
            "dict": "dict[str, Any]",
        }
        if type_hint.startswith("list["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "Any"
            return f"list[{self._map_type(inner)}]"
        if type_hint.startswith("dict["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "Any, Any"
            parts = inner.split(",", 1)
            k = self._map_type(parts[0].strip()) if parts else "Any"
            v = self._map_type(parts[1].strip()) if len(parts) > 1 else "Any"
            return f"dict[{k}, {v}]"
        return type_map.get(type_hint, type_hint)

    def emit(self, spec: EngineSpec) -> str:
        """Render *spec* and normalize every generated class to have ``__init__``."""
        source = super().emit(spec)
        from aero_forge.scaffold.syntax_guard import normalize_python_module

        return normalize_python_module(source)

    def _bool_literal(self, value: bool) -> str:
        return "True" if value else "False"

    def _none_literal(self) -> str:
        return "None"

    def _list_literal(self, children: List[ASTNode]) -> str:
        items = ", ".join(self._expr(c) for c in children)
        return f"[{items}]"

    def _dict_literal(self, pairs: List[ASTNode]) -> str:
        entries = []
        for pair in pairs:
            k, v = pair.children
            entries.append(f"{self._expr(k)}: {self._expr(v)}")
        return "{" + ", ".join(entries) + "}"


class PythonEmitterPlugin(PolyglotEmitterPlugin):
    """Polyglot plugin adapter for the Python emitter."""

    @property
    def descriptor(self) -> CapabilityDescriptor:
        return CapabilityDescriptor(
            language_id="python",
            supported_boundaries={
                BoundaryContract.C_ABI,
                BoundaryContract.PYO3_MATURIN,
            },
            toolchains=["cpython", "maturin"],
            file_extensions=[".py"],
            supports_zero_copy=False,
            supports_async_ffi=False,
        )

    def emit_source_files(
        self,
        node_id: str,
        node_spec: dict,
        boundary_contracts: List[dict],
    ) -> List[CodeArtifact]:
        source_files = node_spec.get("source_files") or [f"{node_id or 'module'}.py"]
        file_path = str(source_files[0])
        # GraphPolyglotMaterializer already writes artifacts under the node
        # directory, so strip an explicit leading node_id/ prefix to avoid
        # double-nested paths.
        prefix = f"{node_id}/"
        if file_path.startswith(prefix):
            file_path = file_path[len(prefix):]

        if _has_pyo3_consumer_contract(node_id, boundary_contracts):
            source = _pyo3_loader_source(node_id, boundary_contracts, node_spec)
        elif _has_c_abi_consumer_contract(node_id, boundary_contracts):
            source = _ctypes_loader_source(node_id, boundary_contracts, node_spec)
        else:
            spec = _engine_spec_from_node_spec(node_id, node_spec)
            source = PythonEmitter().emit(spec)
        return [CodeArtifact(file_path=file_path, content=source, language="python")]

    def emit_build_manifest(
        self,
        node_id: str,
        dependencies: List[str],
        compiler_flags: List[str],
    ) -> CodeArtifact:
        deps = "\n".join(f'    "{d}",' for d in dependencies)
        content = (
            "[build-system]\n"
            'requires = ["setuptools>=61.0", "wheel"]\n'
            'build-backend = "setuptools.build_meta"\n\n'
            "[project]\n"
            f'name = "{node_id or "project"}"\n'
            'version = "0.1.0"\n'
            "[project.dependencies]\n"
            f"{deps}\n"
        )
        return CodeArtifact(
            file_path="pyproject.toml", content=content, language="toml"
        )


def _has_pyo3_consumer_contract(node_id: str, boundary_contracts: List[dict]) -> bool:
    """Return True when *node_id* is the Python consumer side of a PyO3 edge."""
    for contract in boundary_contracts:
        boundary = str(contract.get("boundary_type") or contract.get("boundary") or "c_abi").lower().replace("-", "_")
        if (
            boundary in ("pyo3", "pyo3_maturin", "maturin")
            and contract.get("target") == node_id
        ):
            return True
    return False


def _has_c_abi_consumer_contract(node_id: str, boundary_contracts: List[dict]) -> bool:
    """Return True when *node_id* is the Python consumer side of a C-ABI edge."""
    for contract in boundary_contracts:
        if (
            contract.get("boundary_type") == "c_abi"
            and contract.get("target") == node_id
        ):
            return True
    return False


def _demo_call_args(args: List[str]) -> str:
    """Return a literal argument list for the CLI demo call.

    Use integer literals for every numeric type.  PyO3 accepts Python ints for
    both integer and float parameters, but a float will raise when the Rust
    function expects an integer.
    """
    parts: List[str] = []
    for a in args:
        if a == "pointer":
            parts.append("[1.0, 2.0, 3.0, 4.0]")
        elif a in ("float32", "float64", "int32", "int64"):
            parts.append("42")
        else:
            parts.append("42")
    return ", ".join(parts)


def _pyo3_loader_source(
    node_id: str,
    boundary_contracts: List[dict],
    node_spec: Optional[dict] = None,
) -> str:
    """Generate a Python CLI that imports a compiled PyO3/Maturin extension."""
    pyo3_contracts = [
        c
        for c in boundary_contracts
        if str(c.get("boundary_type") or c.get("boundary") or "").lower().replace("-", "_") in ("pyo3", "pyo3_maturin", "maturin")
        and c.get("target") == node_id
    ]
    default_contract = pyo3_contracts[0] if pyo3_contracts else {}

    exports = list((node_spec or {}).get("exports") or [default_contract.get("symbol", "rust_core")])
    exports = [n for n in exports if n]
    if not exports:
        exports = [default_contract.get("symbol", "rust_core")]
    primary = exports[0]

    def _contract_for_export(index: int, name: str) -> dict:
        # Pair exported Python wrappers with PyO3 contracts in declaration order;
        # fall back to a symbol-name match or the first contract.
        if index < len(pyo3_contracts):
            return pyo3_contracts[index]
        for c in pyo3_contracts:
            if c.get("symbol") == name:
                return c
        return default_contract

    wrappers: List[str] = []
    for idx, export_name in enumerate(exports):
        contract = _contract_for_export(idx, export_name)
        source_node = contract.get("source", default_contract.get("source", "rust_core"))
        symbol = contract.get("symbol", export_name)
        wrappers.extend(
            [
                f"def {export_name}(*args, **kwargs):",
                f"    from {source_node} import {symbol} as _impl",
                "    return _impl(*args, **kwargs)",
                "",
            ]
        )
    wrapper_block = "\n".join(wrappers)

    primary_contract = _contract_for_export(0, primary)
    call_args = _demo_call_args(primary_contract.get("args", ["int64"]))

    return f'''"""Auto-generated Python CLI for the PyO3/Maturin bridge."""
from typing import Any

{wrapper_block}
if __name__ == "__main__":
    result = {primary}({call_args})
    print(f"{primary}({call_args}) = {{result}}")
'''


def _ctypes_loader_source(
    node_id: str,
    boundary_contracts: List[dict],
    node_spec: Optional[dict] = None,
) -> str:
    """Generate a Python CLI that loads the source node's C-ABI shared library."""
    contracts = [
        c
        for c in boundary_contracts
        if c.get("boundary_type") == "c_abi" and c.get("target") == node_id
    ]
    if not contracts:
        contracts = [
            next(
                (
                    c
                    for c in boundary_contracts
                    if c.get("boundary_type") == "c_abi"
                ),
                {},
            )
        ]
    source_node = contracts[0].get("source", "native_kernel")

    # The boundary contracts may be simplified by the orchestrator; prefer the
    # richer signatures stored in the Compacted Functional Matrix when available.
    compacted = (node_spec or {}).get("_compacted_context") or {}
    if isinstance(compacted, str):
        try:
            compacted = json.loads(compacted)
        except Exception:
            compacted = {}
    compacted_contracts = (compacted or {}).get("contracts") or []
    for contract in contracts:
        for cc in compacted_contracts:
            if (
                cc.get("symbol") == contract.get("symbol")
                and cc.get("source", contract.get("source"))
                == contract.get("source")
                and cc.get("target", contract.get("target"))
                == contract.get("target")
            ):
                if cc.get("args") and len(cc["args"]) >= len(contract.get("args") or []):
                    contract["args"] = list(cc["args"])
                if cc.get("return_type"):
                    contract["return_type"] = cc["return_type"]
                break

    ctype_for = {
        "int32": "ctypes.c_int32",
        "int64": "ctypes.c_int64",
        "float32": "ctypes.c_float",
        "float64": "ctypes.c_double",
        "pointer": "ctypes.POINTER(ctypes.c_double)",
    }
    py_type_for = {
        "int32": "int",
        "int64": "int",
        "float32": "float",
        "float64": "float",
        "pointer": "List[float]",
    }

    def _arg_name(i: int) -> str:
        return f"arg{i}"

    wrappers: List[str] = []
    main_calls: List[str] = []
    demo_limit = 100
    for contract in contracts:
        symbol = contract.get("symbol", "fast_math_kernel")
        args = list(contract.get("args") or ["int64"])
        return_type = contract.get("return_type", "int64") or "int64"
        argtypes = ", ".join(ctype_for.get(a, "ctypes.c_int64") for a in args)
        restype = ctype_for.get(return_type, "ctypes.c_int64")

        wrappers.append(f'_c_{symbol} = getattr(_LIB, "{symbol}", None)')
        wrappers.append(f'if _c_{symbol} is None:')
        wrappers.append(f'    _c_{symbol} = getattr(_LIB, "_{symbol}", None)')
        wrappers.append(f'if _c_{symbol} is None:')
        wrappers.append(f'    _c_{symbol} = getattr(_LIB, "{symbol}_", None)')
        wrappers.append(f'if _c_{symbol} is None:')
        wrappers.append(f'    raise AttributeError(f"Symbol {symbol!r} not found in {{_LIB_NAME}}")')
        wrappers.append(f"_c_{symbol}.argtypes = [{argtypes}]")
        wrappers.append(f"_c_{symbol}.restype = {restype}")

        arg_names = [_arg_name(i) for i in range(len(args))]
        sig_args = ", ".join(
            f"{n}: {py_type_for.get(a, 'int')}" for n, a in zip(arg_names, args)
        ) or "*args"

        # Generic pointer handling: every `pointer` argument is marshalled through a
        # ctypes c_double array whose size is derived from the Python list length.
        # After the native call, changed values are copied back into the Python lists
        # so out-parameters and output buffers both work.
        wrapper_body: List[str] = ["    _bufs: dict = {}"]
        c_call_args: List[str] = []
        for n, a in zip(arg_names, args):
            if a == "pointer":
                wrapper_body.append(f"    _bufs[{n!r}] = (ctypes.c_double * max(len({n}), 1))()")
                wrapper_body.append(f"    for _j, _v in enumerate({n}):")
                wrapper_body.append(f"        if _j < len(_bufs[{n!r}]):")
                wrapper_body.append(f"            _bufs[{n!r}][_j] = _v")
                c_call_args.append(f"_bufs[{n!r}]")
            else:
                c_call_args.append(n)
        wrapper_body.append(f"    _res = _c_{symbol}({', '.join(c_call_args)})")
        for n, a in zip(arg_names, args):
            if a == "pointer":
                wrapper_body.append(f"    for _j in range(min(_res, len({n}))):")
                wrapper_body.append(f"        if _j < len({n}):")
                wrapper_body.append(f"            {n}[_j] = _bufs[{n!r}][_j]")
        wrapper_body.append("    return int(_res)")
        if return_type in ("float32", "float64") and not any(a == "pointer" for a in args):
            wrapper_body[-1] = f"    return float(_res)"

        wrappers.append(f"def {symbol}({sig_args}) -> {py_type_for.get(return_type, 'int')}:")
        wrappers.append(f'    """Python wrapper for the C-ABI symbol `{symbol}`."""')
        wrappers.extend(wrapper_body)
        wrappers.append("")

        # Build a simple main() demo call for this contract.
        call_args: List[str] = []
        pointer_count = 0
        for i, a in enumerate(args):
            if a == "pointer":
                # The first pointer is treated as the output buffer (larger);
                # subsequent pointers are out-parameter slots.
                buf_size = demo_limit if pointer_count == 0 else 1
                buf_var = f"_{symbol}_buf_{pointer_count}"
                main_calls.append(f"    {buf_var} = [0.0] * {buf_size}")
                call_args.append(buf_var)
                pointer_count += 1
            elif a in ("float32", "float64"):
                call_args.append("42.0")
            else:
                call_args.append(str(demo_limit))
        if return_type in ("void", ""):
            main_calls.append(f"    {symbol}({', '.join(call_args)})")
        else:
            main_calls.append(f"    print({symbol}({', '.join(call_args)}))")

    main_lines = [
        'def main(argv=None):',
        '    """CLI entry point that exercises every C-ABI contract."""',
        '    import sys',
        '    if argv is None:',
        '        argv = sys.argv[1:]',
    ] + main_calls + ["    return 0"]

    return f'''"""Auto-generated Python CLI for the C-ABI bridge."""
import ctypes
import sys
from pathlib import Path
from typing import List

_SCRIPT_DIR = Path(__file__).resolve().parent
_LIB_NAME = "lib{source_node}.so"
# The .so is built in the source-node directory. Search up the tree because
# the Python entrypoint may live directly under the node dir or inside a
# nested ``python_interface`` package.
_LIB_PATH = None
for _depth in range(min(4, len(_SCRIPT_DIR.parents))):
    _candidate = _SCRIPT_DIR.parents[_depth] / "{source_node}" / _LIB_NAME
    if _candidate.exists():
        _LIB_PATH = _candidate
        break
if _LIB_PATH is None:
    _LIB_PATH = _SCRIPT_DIR.parent / "{source_node}" / _LIB_NAME

_LIB = ctypes.CDLL(str(_LIB_PATH))

{chr(10).join(wrappers)}
{chr(10).join(main_lines)}

if __name__ == "__main__":
    sys.exit(main())
'''


def _engine_spec_from_node_spec(node_id: str, node_spec: dict) -> EngineSpec:
    """Best-effort conversion of a plugin node spec to an EngineSpec."""
    spec = node_spec.get("spec")
    if isinstance(spec, EngineSpec):
        return spec
    if "source" in node_spec:
        name = node_spec.get("name") or node_id or "module"
        root = module(children=[function(name, body=[])])
        return EngineSpec(name=name, root=root)
    if "root" in node_spec:
        return EngineSpec(
            name=node_spec.get("name", node_id or "module"),
            root=node_spec["root"],
        )
    return EngineSpec(name=node_id or "module", root=module(children=[]))


EmitterRegistry.get_instance().register(PythonEmitterPlugin())
