"""Python target emitter for aero-forge engine specs."""

from __future__ import annotations

from typing import List, Optional

from aero_forge.builder.emitters.base import BaseEmitter
from aero_forge.builder.spec import ASTNode, EngineSpec


class PythonEmitter(BaseEmitter):
    """Emit syntactically valid Python 3 source from an engine spec."""

    target_language = "python"

    def _emit_preamble(self, spec: EngineSpec) -> None:
        self._write('"""Auto-generated by aero-forge polyglot emitter."""')
        self._write("from typing import Any")
        self._write("")

    def _emit_module(self, node: ASTNode, indent_level: int) -> None:
        self._emit_children(node.children, indent_level)

    def _emit_function(self, node: ASTNode, indent_level: int) -> None:
        params = node.params
        param_strs: List[str] = []
        for p in params:
            if p.type_hint:
                param_strs.append(f"{p.name}: {self._map_type(p.type_hint)}")
            else:
                param_strs.append(p.name or "_")

        sig = f"def {node.name}({', '.join(param_strs)})"
        if node.type_hint:
            sig += f" -> {self._map_type(node.type_hint)}"
        sig += ":"

        self._write("")
        self._write(sig, indent_level)
        body = node.body
        if body:
            self._emit_children(body, indent_level + 1)
        else:
            self._write("pass", indent_level + 1)

    def _emit_struct(self, node: ASTNode, indent_level: int) -> None:
        self._write("")
        self._write(f"class {node.name}:", indent_level)
        if node.children:
            for field in node.children:
                if field.kind != "field":
                    continue
                type_str = f": {self._map_type(field.type_hint)}" if field.type_hint else ""
                self._write(f"{field.name}{type_str}", indent_level + 1)
        else:
            self._write("pass", indent_level + 1)

    def _emit_binding(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        if node.type_hint:
            self._write(
                f"{node.name}: {self._map_type(node.type_hint)} = {value_str}",
                indent_level,
            )
        else:
            self._write(f"{node.name} = {value_str}", indent_level)

    def _emit_return(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        self._write(f"return {value_str}", indent_level)

    def _emit_import(self, node: ASTNode, indent_level: int) -> None:
        self._write(f"import {node.value}", indent_level)

    def _emit_comment(self, node: ASTNode, indent_level: int) -> None:
        for line in str(node.value or "").splitlines():
            self._write(f"# {line}", indent_level)

    def _emit_if(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        condition = self._expr(node.children[0])
        self._write(f"if {condition}:", indent_level)
        if len(node.children) > 1:
            self._emit_children(node.children[1].children, indent_level + 1)
        else:
            self._write("pass", indent_level + 1)
        if len(node.children) > 2:
            self._write("else:", indent_level)
            self._emit_children(node.children[2].children, indent_level + 1)

    def _map_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "Any"
        type_map = {
            "int": "int",
            "i32": "int",
            "i64": "int",
            "float": "float",
            "f32": "float",
            "f64": "float",
            "double": "float",
            "str": "str",
            "string": "str",
            "bool": "bool",
            "void": "None",
            "None": "None",
            "list": "list[Any]",
            "dict": "dict[str, Any]",
        }
        if type_hint.startswith("list["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "Any"
            return f"list[{self._map_type(inner)}]"
        if type_hint.startswith("dict["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "Any, Any"
            parts = inner.split(",", 1)
            k = self._map_type(parts[0].strip()) if parts else "Any"
            v = self._map_type(parts[1].strip()) if len(parts) > 1 else "Any"
            return f"dict[{k}, {v}]"
        return type_map.get(type_hint, type_hint)

    def _bool_literal(self, value: bool) -> str:
        return "True" if value else "False"

    def _none_literal(self) -> str:
        return "None"

    def _list_literal(self, children: List[ASTNode]) -> str:
        items = ", ".join(self._expr(c) for c in children)
        return f"[{items}]"

    def _dict_literal(self, pairs: List[ASTNode]) -> str:
        entries = []
        for pair in pairs:
            k, v = pair.children
            entries.append(f"{self._expr(k)}: {self._expr(v)}")
        return "{" + ", ".join(entries) + "}"
