"""Python target emitter for aero-forge engine specs."""

from __future__ import annotations

import ast
from typing import List, Optional

from aero_forge.builder.emitters.base import (
    BaseEmitter,
    BoundaryContract,
    CapabilityDescriptor,
    CodeArtifact,
    EmitterRegistry,
    PolyglotEmitterPlugin,
)
from aero_forge.builder.spec import ASTNode, EngineSpec, function, module


class PythonEmitter(BaseEmitter):
    """Emit syntactically valid Python 3 source from an engine spec."""

    target_language = "python"

    def _emit_preamble(self, spec: EngineSpec) -> None:
        self._write('"""Auto-generated by aero-forge polyglot emitter."""')
        self._write("from typing import Any, List, Dict, Optional")
        self._write("")

    def _emit_module(self, node: ASTNode, indent_level: int) -> None:
        self._emit_children(node.children, indent_level)

    def _emit_function(self, node: ASTNode, indent_level: int) -> None:
        params = node.params
        param_strs: List[str] = []
        for p in params:
            if p.type_hint:
                param_strs.append(f"{p.name}: {self._map_type(p.type_hint)}")
            else:
                param_strs.append(p.name or "_")
        # Variadic fallback so caller arity mismatches do not crash execution.
        param_strs.extend(["*args", "**kwargs"])

        sig = f"def {node.name}({', '.join(param_strs)})"
        if node.type_hint:
            sig += f" -> {self._map_type(node.type_hint)}"
        sig += ":"

        self._write("")
        self._write(sig, indent_level)
        body = node.body
        if body:
            self._emit_children(body, indent_level + 1)
        else:
            self._write("pass", indent_level + 1)

    def _emit_struct(self, node: ASTNode, indent_level: int) -> None:
        self._write("")
        self._write(f"class {node.name}:", indent_level)
        if node.children:
            for field in node.children:
                if field.kind != "field":
                    continue
                type_str = (
                    f": {self._map_type(field.type_hint)}" if field.type_hint else ""
                )
                self._write(f"{field.name}{type_str}", indent_level + 1)
        else:
            self._write("pass", indent_level + 1)

    def _emit_binding(self, node: ASTNode, indent_level: int) -> None:
        value_str = (
            self._expr(node.children[0]) if node.children else self._literal(node.value)
        )
        if node.type_hint:
            self._write(
                f"{node.name}: {self._map_type(node.type_hint)} = {value_str}",
                indent_level,
            )
        else:
            self._write(f"{node.name} = {value_str}", indent_level)

    def _emit_return(self, node: ASTNode, indent_level: int) -> None:
        value_str = (
            self._expr(node.children[0]) if node.children else self._literal(node.value)
        )
        self._write(f"return {value_str}", indent_level)

    def _emit_import(self, node: ASTNode, indent_level: int) -> None:
        self._write(f"import {node.value}", indent_level)

    def _emit_comment(self, node: ASTNode, indent_level: int) -> None:
        for line in str(node.value or "").splitlines():
            self._write(f"# {line}", indent_level)

    def _emit_if(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        condition = self._expr(node.children[0])
        self._write(f"if {condition}:", indent_level)
        if len(node.children) > 1:
            self._emit_children(node.children[1].children, indent_level + 1)
        else:
            self._write("pass", indent_level + 1)
        if len(node.children) > 2:
            self._write("else:", indent_level)
            self._emit_children(node.children[2].children, indent_level + 1)

    def _map_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "Any"
        type_map = {
            "int": "int",
            "i32": "int",
            "i64": "int",
            "float": "float",
            "f32": "float",
            "f64": "float",
            "double": "float",
            "str": "str",
            "string": "str",
            "bool": "bool",
            "void": "None",
            "None": "None",
            "list": "list[Any]",
            "dict": "dict[str, Any]",
        }
        if type_hint.startswith("list["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "Any"
            return f"list[{self._map_type(inner)}]"
        if type_hint.startswith("dict["):
            inner = type_hint[5:-1] if type_hint.endswith("]") else "Any, Any"
            parts = inner.split(",", 1)
            k = self._map_type(parts[0].strip()) if parts else "Any"
            v = self._map_type(parts[1].strip()) if len(parts) > 1 else "Any"
            return f"dict[{k}, {v}]"
        return type_map.get(type_hint, type_hint)

    def emit(self, spec: EngineSpec) -> str:
        """Render *spec* and normalize every generated class to have ``__init__``."""
        source = super().emit(spec)
        from aero_forge.scaffold.syntax_guard import normalize_python_module

        return normalize_python_module(source)

    def _bool_literal(self, value: bool) -> str:
        return "True" if value else "False"

    def _none_literal(self) -> str:
        return "None"

    def _list_literal(self, children: List[ASTNode]) -> str:
        items = ", ".join(self._expr(c) for c in children)
        return f"[{items}]"

    def _dict_literal(self, pairs: List[ASTNode]) -> str:
        entries = []
        for pair in pairs:
            k, v = pair.children
            entries.append(f"{self._expr(k)}: {self._expr(v)}")
        return "{" + ", ".join(entries) + "}"


class PythonEmitterPlugin(PolyglotEmitterPlugin):
    """Polyglot plugin adapter for the Python emitter."""

    @property
    def descriptor(self) -> CapabilityDescriptor:
        return CapabilityDescriptor(
            language_id="python",
            supported_boundaries={
                BoundaryContract.C_ABI,
                BoundaryContract.PYO3_MATURIN,
            },
            toolchains=["cpython", "maturin"],
            file_extensions=[".py"],
            supports_zero_copy=False,
            supports_async_ffi=False,
        )

    def emit_source_files(
        self,
        node_id: str,
        node_spec: dict,
        boundary_contracts: List[dict],
    ) -> List[CodeArtifact]:
        source_files = node_spec.get("source_files") or [f"{node_id or 'module'}.py"]
        file_path = str(source_files[0])
        # GraphPolyglotMaterializer already writes artifacts under the node
        # directory, so strip an explicit leading node_id/ prefix to avoid
        # double-nested paths.
        prefix = f"{node_id}/"
        if file_path.startswith(prefix):
            file_path = file_path[len(prefix):]

        if _has_pyo3_consumer_contract(node_id, boundary_contracts):
            source = _pyo3_loader_source(node_id, boundary_contracts)
        elif _has_c_abi_consumer_contract(node_id, boundary_contracts):
            source = _ctypes_loader_source(node_id, boundary_contracts)
        else:
            spec = _engine_spec_from_node_spec(node_id, node_spec)
            source = PythonEmitter().emit(spec)
        return [CodeArtifact(file_path=file_path, content=source, language="python")]

    def emit_build_manifest(
        self,
        node_id: str,
        dependencies: List[str],
        compiler_flags: List[str],
    ) -> CodeArtifact:
        deps = "\n".join(f'    "{d}",' for d in dependencies)
        content = (
            "[build-system]\n"
            'requires = ["setuptools>=61.0", "wheel"]\n'
            'build-backend = "setuptools.build_meta"\n\n'
            "[project]\n"
            f'name = "{node_id or "project"}"\n'
            'version = "0.1.0"\n'
            "[project.dependencies]\n"
            f"{deps}\n"
        )
        return CodeArtifact(
            file_path="pyproject.toml", content=content, language="toml"
        )


def _has_pyo3_consumer_contract(node_id: str, boundary_contracts: List[dict]) -> bool:
    """Return True when *node_id* is the Python consumer side of a PyO3 edge."""
    for contract in boundary_contracts:
        boundary = str(contract.get("boundary_type") or contract.get("boundary") or "c_abi").lower().replace("-", "_")
        if (
            boundary in ("pyo3", "pyo3_maturin", "maturin")
            and contract.get("target") == node_id
        ):
            return True
    return False


def _has_c_abi_consumer_contract(node_id: str, boundary_contracts: List[dict]) -> bool:
    """Return True when *node_id* is the Python consumer side of a C-ABI edge."""
    for contract in boundary_contracts:
        if (
            contract.get("boundary_type") == "c_abi"
            and contract.get("target") == node_id
        ):
            return True
    return False


def _demo_call_args(args: List[str]) -> str:
    """Return a literal argument list for the CLI demo call."""
    parts: List[str] = []
    for a in args:
        if a == "pointer":
            parts.append("[1.0, 2.0, 3.0, 4.0]")
        elif a in ("float32", "float64"):
            parts.append("42.0")
        elif a in ("int32", "int64"):
            parts.append("42")
        else:
            parts.append("42")
    return ", ".join(parts)


def _pyo3_loader_source(node_id: str, boundary_contracts: List[dict]) -> str:
    """Generate a Python CLI that imports a compiled PyO3/Maturin extension."""
    contract = next(
        (
            c
            for c in boundary_contracts
            if str(c.get("boundary_type") or c.get("boundary") or "").lower().replace("-", "_") in ("pyo3", "pyo3_maturin", "maturin")
            and c.get("target") == node_id
        ),
        {},
    )
    source_node = contract.get("source", "rust_core")
    symbol = contract.get("symbol", source_node)
    args = contract.get("args", ["int64"])
    call_args = _demo_call_args(args)

    return f'''"""Auto-generated Python CLI for the PyO3/Maturin bridge."""
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
# The compiled Rust extension is a sibling package (e.g. rust_core/__init__.py).
if str(_SCRIPT_DIR.parent) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR.parent))

from {source_node} import {symbol}

if __name__ == "__main__":
    result = {symbol}({call_args})
    print(f"{symbol}({call_args}) = {{result}}")
'''


def _ctypes_loader_source(node_id: str, boundary_contracts: List[dict]) -> str:
    """Generate a Python CLI that loads the source node's C-ABI shared library."""
    contract = next(
        (
            c
            for c in boundary_contracts
            if c.get("boundary_type") == "c_abi" and c.get("target") == node_id
        ),
        {},
    )
    source_node = contract.get("source", "native_kernel")
    symbol = contract.get("symbol", "fast_math_kernel")
    args = contract.get("args", ["int64"])
    return_type = contract.get("return_type", "int64") or "int64"

    ctype_for = {
        "int32": "ctypes.c_int32",
        "int64": "ctypes.c_int64",
        "float32": "ctypes.c_float",
        "float64": "ctypes.c_double",
        "pointer": "ctypes.POINTER(ctypes.c_double)",
    }
    argtypes = ", ".join(ctype_for.get(a, "ctypes.c_int64") for a in args)
    restype = ctype_for.get(return_type, "ctypes.c_int64")

    call_args = _demo_call_args(args)
    call = f"{symbol}({call_args})"

    return f'''"""Auto-generated Python CLI for the C-ABI bridge."""
import ctypes
import os
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
_LIB_NAME = "lib{source_node}.so"
_LIB_PATH: Path | None = None
for _p in (_SCRIPT_DIR, *_SCRIPT_DIR.parents):
    _candidate = _p / "{source_node}" / _LIB_NAME
    if _candidate.exists():
        _LIB_PATH = _candidate
        break
if _LIB_PATH is None:
    # Fall back to a conventional sibling layout.
    _LIB_PATH = _SCRIPT_DIR.parent / "{source_node}" / _LIB_NAME

_LIB = ctypes.CDLL(str(_LIB_PATH))

# Prefer the unmangled symbol; allow common prefix variations if the ABI
# boundary used different naming conventions.
{symbol} = getattr(_LIB, "{symbol}", None)
if {symbol} is None:
    {symbol} = getattr(_LIB, "_{symbol}", None)
if {symbol} is None:
    {symbol} = getattr(_LIB, "{symbol}_", None)
if {symbol} is None:
    raise AttributeError(f"Symbol {symbol!r} not found in {{_LIB_NAME}}")
{symbol}.argtypes = [{argtypes}]
{symbol}.restype = {restype}

if __name__ == "__main__":
    result = {call}
    print(f"{symbol}({call_args}) = {{result}}")
'''


def _engine_spec_from_node_spec(node_id: str, node_spec: dict) -> EngineSpec:
    """Best-effort conversion of a plugin node spec to an EngineSpec."""
    spec = node_spec.get("spec")
    if isinstance(spec, EngineSpec):
        return spec
    if "source" in node_spec:
        name = node_spec.get("name") or node_id or "module"
        root = module(children=[function(name, body=[])])
        return EngineSpec(name=name, root=root)
    if "root" in node_spec:
        return EngineSpec(
            name=node_spec.get("name", node_id or "module"),
            root=node_spec["root"],
        )
    return EngineSpec(name=node_id or "module", root=module(children=[]))


EmitterRegistry.get_instance().register(PythonEmitterPlugin())
