"""Rust target emitter for aero-forge engine specs."""

from __future__ import annotations

from typing import List, Optional

from aero_forge.builder.emitters.base import BaseEmitter
from aero_forge.builder.spec import ASTNode, EngineSpec


class RustEmitter(BaseEmitter):
    """Emit syntactically valid Rust source from an engine spec."""

    target_language = "rust"

    def _emit_preamble(self, spec: EngineSpec) -> None:
        self._write("// Auto-generated by aero-forge polyglot emitter.")
        self._write("")

    def _emit_module(self, node: ASTNode, indent_level: int) -> None:
        self._emit_children(node.children, indent_level)

    def _emit_function(self, node: ASTNode, indent_level: int) -> None:
        params = node.params
        param_strs: List[str] = []
        for p in params:
            if p.name == "self":
                param_strs.append("&self")
            elif p.type_hint:
                param_strs.append(f"{p.name}: {self._map_type(p.type_hint)}")
            else:
                param_strs.append(f"{p.name}: ()")

        sig = f"fn {node.name}({', '.join(param_strs)})"
        if node.type_hint:
            sig += f" -> {self._map_type(node.type_hint)}"

        self._write("")
        self._write(f"pub {sig} {{", indent_level)
        body = node.body
        if body:
            self._emit_children(body, indent_level + 1)
        else:
            self._write("todo!()", indent_level + 1)
        self._write("}", indent_level)

    def _emit_struct(self, node: ASTNode, indent_level: int) -> None:
        self._write("")
        self._write(f"pub struct {node.name} {{", indent_level)
        for field in node.children:
            if field.kind != "field":
                continue
            type_str = self._map_type(field.type_hint) if field.type_hint else "()"
            self._write(f"pub {field.name}: {type_str},", indent_level + 1)
        self._write("}", indent_level)

    def _emit_binding(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        if node.type_hint:
            self._write(
                f"let {node.name}: {self._map_type(node.type_hint)} = {value_str};",
                indent_level,
            )
        else:
            self._write(f"let {node.name} = {value_str};", indent_level)

    def _emit_return(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        self._write(f"return {value_str};", indent_level)

    def _emit_import(self, node: ASTNode, indent_level: int) -> None:
        self._write(f"use {node.value};", indent_level)

    def _emit_comment(self, node: ASTNode, indent_level: int) -> None:
        for line in str(node.value or "").splitlines():
            self._write(f"// {line}", indent_level)

    def _emit_if(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        condition = self._expr(node.children[0])
        self._write(f"if {condition} {{", indent_level)
        if len(node.children) > 1:
            self._emit_children(node.children[1].children, indent_level + 1)
        self._write("}", indent_level)
        if len(node.children) > 2:
            self._write("else {", indent_level)
            self._emit_children(node.children[2].children, indent_level + 1)
            self._write("}", indent_level)

    def _map_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "()"
        type_map = {
            "int": "i64",
            "float": "f64",
            "double": "f64",
            "str": "String",
            "string": "String",
            "bool": "bool",
            "void": "()",
            "None": "()",
            "list": "Vec<()>",
            "dict": "std::collections::HashMap<String, ()>",
            "char": "char",
            "unsigned int": "u64",
            "long": "i64",
            "short": "i16",
            "size_t": "usize",
        }
        if type_hint.startswith("list[") and type_hint.endswith("]"):
            inner = type_hint[5:-1]
            return f"Vec<{self._map_type(inner)}>"
        if type_hint.startswith("dict[") and type_hint.endswith("]"):
            inner = type_hint[5:-1]
            if "," in inner:
                k, v = inner.split(",", 1)
                return f"std::collections::HashMap<{self._map_type(k.strip())}, {self._map_type(v.strip())}>"
            return f"std::collections::HashMap<String, {self._map_type(inner)}>"
        return type_map.get(type_hint, type_hint)

    def _bool_literal(self, value: bool) -> str:
        return "true" if value else "false"

    def _none_literal(self) -> str:
        return "()"

    def _list_literal(self, children: List[ASTNode]) -> str:
        items = ", ".join(self._expr(c) for c in children)
        return f"vec![{items}]"

    def _dict_literal(self, pairs: List[ASTNode]) -> str:
        entries = []
        for pair in pairs:
            k, v = pair.children
            entries.append(f"({self._expr(k)}, {self._expr(v)})")
        if not entries:
            return "std::collections::HashMap::new()"
        return f"std::collections::HashMap::from([{', '.join(entries)}])"

    def _emit_expression_to_string(self, node: ASTNode) -> str:
        if node.kind == "binary_op" and node.name == "**":
            base, exp = node.children
            return f"{self._expr(base)}.pow({self._expr(exp)} as u32)"
        return super()._emit_expression_to_string(node)
