"""Rust target emitter for aero-forge engine specs."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from aero_forge.builder.artifact_generator import Artifact, ArtifactBundle
from aero_forge.builder.emitters.base import BaseEmitter
from aero_forge.builder.spec import ASTNode, EngineSpec


class RustEmitter(BaseEmitter):
    """Emit syntactically valid Rust source from an engine spec."""

    target_language = "rust"

    # Tracks extra Rust module files requested by the spec metadata.
    module_sources: Dict[str, str]
    module_artifacts: ArtifactBundle

    def __init__(self, indent: Optional[str] = None) -> None:
        super().__init__(indent=indent)
        self.module_sources = {}
        self.module_artifacts = ArtifactBundle()

    def emit(self, spec: EngineSpec) -> str:
        """Return the fully rendered ``src/lib.rs`` source for *spec*.

        If ``spec.metadata["module_files"]`` is provided, each submodule file
        is rendered into :attr:`module_sources` and registered inside ``lib.rs``
        via ``mod`` declarations and a ``#[pymodule]`` registration block.
        """
        self._lines = []
        self.module_sources = {}
        self.module_artifacts = ArtifactBundle(
            metadata={"project_name": spec.name, "language": "rust"}
        )

        self.is_pyo3 = self._is_pyo3_spec(spec)
        self.uses_numpy = self._uses_numpy(spec)
        self.uses_rayon = self._uses_rayon(spec)

        module_files = spec.metadata.get("module_files") or []
        root_functions = [
            c for c in spec.root.children if c.kind == "function"
        ]
        module_registrations: List[Tuple[str, str]] = []

        for mf in module_files:
            mod_root = mf.get("root") or ASTNode(kind="module", name="module", children=[])
            mod_path = str(mf.get("path", "src/mod.rs"))
            mod_name = self._module_name_from_path(mod_path)
            mod_source = self._emit_module_file(mod_root, mod_name)
            self.module_sources[mod_path] = mod_source
            self.module_artifacts.artifacts.append(
                Artifact(path=mod_path, content=mod_source)
            )
            for child in mod_root.children:
                if child.kind == "function" and child.name:
                    module_registrations.append((mod_name, child.name))

        self._emit_preamble(spec)

        # Submodule declarations come before the lib's own items.
        for mod_path in self.module_sources:
            mod_name = self._module_name_from_path(mod_path)
            self._write(f"pub mod {mod_name};")
        if self.module_sources:
            self._write("")

        self._emit(spec.root, 0)

        if self.is_pyo3 and (root_functions or module_registrations):
            self._emit_pymodule_block(spec, root_functions, module_registrations)

        self._emit_postamble(spec)
        return "\n".join(self._lines) + "\n"

    def emit_artifacts(self) -> ArtifactBundle:
        """Return any submodule artifacts produced during the last ``emit`` call."""
        return self.module_artifacts

    # ------------------------------------------------------------------
    # Preamble / postamble
    # ------------------------------------------------------------------

    def _emit_preamble(self, spec: EngineSpec) -> None:
        self._write("// Auto-generated by aero-forge polyglot emitter.")
        if self.is_pyo3:
            self._write("use pyo3::prelude::*;")
            if self.uses_numpy:
                self._write("use numpy::PyArray2;")
        if self.uses_rayon:
            self._write("use rayon::prelude::*;")
        if self.uses_numpy and not self.is_pyo3:
            self._write("use ndarray::{Array2, ArrayView2};")
        self._write("")

    # ------------------------------------------------------------------
    # Language-specific emission hooks
    # ------------------------------------------------------------------

    def _emit_module(self, node: ASTNode, indent_level: int) -> None:
        self._emit_children(node.children, indent_level)

    def _emit_function(self, node: ASTNode, indent_level: int) -> None:
        params = node.params
        param_strs: List[str] = []
        for p in params:
            if p.name == "self":
                param_strs.append("&self")
            elif p.type_hint:
                param_strs.append(f"{p.name}: {self._map_type(p.type_hint)}")
            else:
                param_strs.append(f"{p.name}: ()")

        sig = f"fn {node.name}({', '.join(param_strs)})"
        if node.type_hint:
            sig += f" -> {self._map_type(node.type_hint)}"

        self._write("")
        if self.is_pyo3:
            self._write(f'#[pyfunction(name = "{node.name}")]')
        self._write(f"pub {sig} {{", indent_level)
        body = node.body
        if body:
            self._emit_children(body, indent_level + 1)
        else:
            self._write("todo!()", indent_level + 1)
        self._write("}", indent_level)

    def _emit_struct(self, node: ASTNode, indent_level: int) -> None:
        self._write("")
        self._write(f"pub struct {node.name} {{", indent_level)
        for field in node.children:
            if field.kind != "field":
                continue
            type_str = self._map_type(field.type_hint) if field.type_hint else "()"
            self._write(f"pub {field.name}: {type_str},", indent_level + 1)
        self._write("}", indent_level)

    def _emit_binding(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        if node.type_hint:
            self._write(
                f"let {node.name}: {self._map_type(node.type_hint)} = {value_str};",
                indent_level,
            )
        else:
            self._write(f"let {node.name} = {value_str};", indent_level)

    def _emit_return(self, node: ASTNode, indent_level: int) -> None:
        value_str = self._expr(node.children[0]) if node.children else self._literal(node.value)
        self._write(f"return {value_str};", indent_level)

    def _emit_import(self, node: ASTNode, indent_level: int) -> None:
        self._write(f"use {node.value};", indent_level)

    def _emit_comment(self, node: ASTNode, indent_level: int) -> None:
        for line in str(node.value or "").splitlines():
            self._write(f"// {line}", indent_level)

    def _emit_if(self, node: ASTNode, indent_level: int) -> None:
        if not node.children:
            return
        condition = self._expr(node.children[0])
        self._write(f"if {condition} {{", indent_level)
        if len(node.children) > 1:
            self._emit_children(node.children[1].children, indent_level + 1)
        self._write("}", indent_level)
        if len(node.children) > 2:
            self._write("else {", indent_level)
            self._emit_children(node.children[2].children, indent_level + 1)
            self._write("}", indent_level)

    def _emit_gil_release(self, node: ASTNode, indent_level: int) -> None:
        """Emit ``py.allow_threads(|| { ... })`` around a block of statements."""
        self._write("py.allow_threads(|| {", indent_level)
        self._emit_children(node.children, indent_level + 1)
        self._write("})", indent_level)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _map_type(self, type_hint: Optional[str]) -> str:
        if not type_hint:
            return "()"
        hint = type_hint.strip()

        # Preserve explicit PyO3 / numpy-rust signatures.
        if hint.startswith("PyResult<"):
            inner = hint[9:].strip()
            if inner.endswith(">"):
                inner = inner[:-1].strip()
            return f"PyResult<{self._map_type(inner)}>"

        if hint in ("Python", "Py"):
            return "Python"

        if re.match(r"^&?PyArray\d*<", hint) or hint in (
            "np.ndarray",
            "numpy.ndarray",
            "ndarray",
        ):
            # Default 2-D f64 numpy array for unqualified ndarray annotations.
            if re.search(r"<[^>]+>", hint):
                inner_match = re.search(r"<([^>]+)>", hint)
                inner = inner_match.group(1).strip() if inner_match else "f64"  # type: ignore[union-attr]
                return f"&PyArray2<{inner}>"
            return "&PyArray2<f64>"

        type_map = {
            "int": "i64",
            "float": "f64",
            "double": "f64",
            "str": "String",
            "string": "String",
            "String": "String",
            "bool": "bool",
            "void": "()",
            "None": "()",
            "list": "Vec<()>",
            "dict": "std::collections::HashMap<String, ()>",
            "char": "char",
            "unsigned int": "u64",
            "long": "i64",
            "short": "i16",
            "size_t": "usize",
            "usize": "usize",
            "i64": "i64",
            "f64": "f64",
            "u64": "u64",
            "i32": "i32",
            "u32": "u32",
        }

        if hint.startswith("list[") and hint.endswith("]"):
            inner = hint[5:-1]
            return f"Vec<{self._map_type(inner)}>"
        if hint.startswith("dict[") and hint.endswith("]"):
            inner = hint[5:-1]
            if "," in inner:
                k, v = inner.split(",", 1)
                return f"std::collections::HashMap<{self._map_type(k.strip())}, {self._map_type(v.strip())}>"
            return f"std::collections::HashMap<String, {self._map_type(inner)}>"
        return type_map.get(hint, hint)

    def _bool_literal(self, value: bool) -> str:
        return "true" if value else "false"

    def _none_literal(self) -> str:
        return "()"

    def _list_literal(self, children: List[ASTNode]) -> str:
        items = ", ".join(self._expr(c) for c in children)
        return f"vec![{items}]"

    def _dict_literal(self, pairs: List[ASTNode]) -> str:
        entries = []
        for pair in pairs:
            k, v = pair.children
            entries.append(f"({self._expr(k)}, {self._expr(v)})")
        if not entries:
            return "std::collections::HashMap::new()"
        return f"std::collections::HashMap::from([{', '.join(entries)}])"

    def _emit_expression_to_string(self, node: ASTNode) -> str:
        if node.kind == "binary_op" and node.name == "**":
            base, exp = node.children
            return f"{self._expr(base)}.pow({self._expr(exp)} as u32)"
        return super()._emit_expression_to_string(node)

    # ------------------------------------------------------------------
    # PyO3 / module helpers
    # ------------------------------------------------------------------

    def _is_pyo3_spec(self, spec: EngineSpec) -> bool:
        if spec.metadata.get("pyo3"):
            return True
        for node in self._all_nodes(spec.root):
            if node.type_hint and any(
                pat in node.type_hint
                for pat in ("PyArray", "Python", "PyResult", "Py<", "&Py")
            ):
                return True
        return False

    def _uses_numpy(self, spec: EngineSpec) -> bool:
        if spec.metadata.get("numpy"):
            return True
        for node in self._all_nodes(spec.root):
            if node.type_hint and (
                "PyArray" in node.type_hint
                or node.type_hint in ("np.ndarray", "numpy.ndarray", "ndarray")
            ):
                return True
        return False

    def _uses_rayon(self, spec: EngineSpec) -> bool:
        if spec.metadata.get("rayon"):
            return True
        for node in self._all_nodes(spec.root):
            value = str(node.value or "")
            name = str(node.name or "")
            if "par_iter" in value or "par_iter" in name:
                return True
        return False

    def _all_nodes(self, root: ASTNode) -> List[ASTNode]:
        nodes: List[ASTNode] = []
        stack = [root]
        while stack:
            node = stack.pop()
            nodes.append(node)
            stack.extend(node.children)
        return nodes

    def _module_name_from_path(self, path: str) -> str:
        name = Path(path).stem
        return re.sub(r"[^0-9a-zA-Z_]+", "_", name).strip("_") or "module"

    def _emit_module_file(self, mod_root: ASTNode, mod_name: str) -> str:
        """Render a submodule file (e.g. ``src/ops.rs``)."""
        old_lines = self._lines
        self._lines = []
        if self.is_pyo3:
            self._write("use pyo3::prelude::*;")
            if self.uses_numpy:
                self._write("use numpy::PyArray2;")
            self._write("")
        self._emit_children(mod_root.children, 0)
        source = "\n".join(self._lines) + "\n"
        self._lines = old_lines
        return source

    def _emit_pymodule_block(
        self,
        spec: EngineSpec,
        root_functions: List[ASTNode],
        module_registrations: List[Tuple[str, str]],
    ) -> None:
        """Emit a ``#[pymodule]`` block that registers all public functions."""
        module_name = self._sanitize_module_name(spec.name)
        self._write("")
        self._write(f"#[pymodule]")
        self._write(f"fn {module_name}(_py: Python, m: &PyModule) -> PyResult<()> {{")
        for func in root_functions:
            if func.name:
                self._write(f'    m.add_wrapped(wrap_pyfunction!({func.name}))?;')
        for mod_name, func_name in module_registrations:
            self._write(f'    m.add_wrapped(wrap_pyfunction!({mod_name}::{func_name}))?;')
        self._write("    Ok(())")
        self._write("}")

    def _sanitize_module_name(self, name: str) -> str:
        sanitized = re.sub(r"[^0-9a-zA-Z_]+", "_", name).strip("_")
        if not sanitized or sanitized[0].isdigit():
            sanitized = "aero_forge_native_" + sanitized
        return sanitized
